#!/bin/bash
# Optimises without fucking up the css attributes which  librsvg needs to recolour the symbols (like red !, green tick for battery and such stuff) ... well, at least in theory, in reality it unleashes the horror of αποφις! :>
find . -type f -name '*.svg' -print0 | while IFS= read -r -d '' file; do sed -i 's/fill=\"/style=\"fill:/g' "$file"; done
