#!/bin/bash
dir="$1"
if [[ -z "$dir" ]]; then
    echo "No directory specified. Working in current directory."
    dir="."
fi
find "$dir" -type f -name '*.svg' -print0 | while IFS= read -r -d '' file; do
    if [[ `grep -i "inkscape\|sodipodi" "$file"` ]]; then
        echo "Optimizing $file"
        svgcleaner-cli "$file" "$file" --keep-singly-grads --keep-absolute-paths --join-style-atts --keep-basic-shapes
    fi
done
