#!/bin/bash
find . -type f -name '*.svg' -print0 | while IFS= read -r -d '' file; do
    if [[ `grep -i "inkscape\|sodipodi\|rgb" "$file"` || "$1" = "-f" ]]; then
        echo "Optimizing $file"
        svgcleaner-cli "$file" "$file" --keep-singly-grads --keep-absolute-paths --join-style-atts --keep-basic-shapes
    fi
done
